// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYa5SDPkeBiL6NJdVjdawIaAMZ-n2zL2E',
    appId: '1:161461461121:web:6e46b4f357652faf7bad80',
    messagingSenderId: '161461461121',
    projectId: 'bus-booking-76f8c',
    authDomain: 'bus-booking-76f8c.firebaseapp.com',
    storageBucket: 'bus-booking-76f8c.firebasestorage.app',
    measurementId: 'G-ZWV4JQTNNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEHS-isZHsk1WHojBOAOeDmC_N2EiXnkI',
    appId: '1:161461461121:android:5e2879da7ca321317bad80',
    messagingSenderId: '161461461121',
    projectId: 'bus-booking-76f8c',
    storageBucket: 'bus-booking-76f8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCc6SilLYHxCulXpUEE0UeKr9y2wE_x5U',
    appId: '1:161461461121:ios:a8204e8fdc0db7b37bad80',
    messagingSenderId: '161461461121',
    projectId: 'bus-booking-76f8c',
    storageBucket: 'bus-booking-76f8c.firebasestorage.app',
    iosBundleId: 'com.example.bookingBus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCc6SilLYHxCulXpUEE0UeKr9y2wE_x5U',
    appId: '1:161461461121:ios:a8204e8fdc0db7b37bad80',
    messagingSenderId: '161461461121',
    projectId: 'bus-booking-76f8c',
    storageBucket: 'bus-booking-76f8c.firebasestorage.app',
    iosBundleId: 'com.example.bookingBus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYa5SDPkeBiL6NJdVjdawIaAMZ-n2zL2E',
    appId: '1:161461461121:web:ee0e6cd162f7fb4f7bad80',
    messagingSenderId: '161461461121',
    projectId: 'bus-booking-76f8c',
    authDomain: 'bus-booking-76f8c.firebaseapp.com',
    storageBucket: 'bus-booking-76f8c.firebasestorage.app',
    measurementId: 'G-CYGHT53EJK',
  );
}
